Adding Game Files Article
altmp/altv-docs-gta pull request #12
Opened 2022-02-18 15:43 UTC by PavlovTM

This PR adds an article which explains the game files with examples, pictures including useful side information.

Perhaps over the top, but very useful to explain modding to newcomers

2022-02-18 22:29 UTC, C0kkie requested changes

2022-02-18 22:29 UTC, C0kkie commented on articles/references/game-files.md
> +### Suffix
The Links in the suffex topics doesnt work

2022-02-18 22:29 UTC, C0kkie commented on articles/references/game-files.md
> +This is an example inside CodeWalker, how Path Nodes look like
Add a line break at the end of line

2022-02-18 22:29 UTC, C0kkie commented on articles/references/game-files.md
> +It contains several Entities,
Add a line break at the end of line

2022-02-18 22:29 UTC, C0kkie commented on articles/references/game-files.md
> +Inside ZModeler, a vehicle in hi@ format looks like this
Add a line break at the end of line

2022-02-18 22:29 UTC, C0kkie commented on articles/references/game-files.md
> +Inside OpenIV, it looks like this
Add a line break at the end of line

2022-02-18 22:29 UTC, C0kkie commented on articles/references/game-files.md
> +Inside OpenIV, an YDR looks like this.
Add a line break at the end of line

2022-02-19 11:19 UTC, PavlovTM commented on articles/references/game-files.md
> +### Suffix
Is there something special about anchor links on the docs site?
It's something so simple

2022-02-19 11:24 UTC, PavlovTM commented on articles/references/game-files.md
> +Inside OpenIV, an YDR looks like this.
Resolved

2022-02-19 11:24 UTC, PavlovTM commented on articles/references/game-files.md
> +Inside OpenIV, it looks like this
Resolved

2022-02-19 11:24 UTC, PavlovTM commented on articles/references/game-files.md
> +Inside ZModeler, a vehicle in hi@ format looks like this
Resolved

2022-02-19 11:24 UTC, PavlovTM commented on articles/references/game-files.md
> +It contains several Entities,
Resolved

2022-02-19 11:24 UTC, PavlovTM commented on articles/references/game-files.md
> +This is an example inside CodeWalker, how Path Nodes look like
Resolved

2022-02-19 18:58 UTC, C0kkie commented on articles/references/game-files.md
> +### Suffix
Use singlehash and lowercase and it should work

2022-04-14 13:13 UTC, PavlovTM commented
Changed, I'd say

2022-04-30 23:48 UTC, Unnvaldr commented on articles/references/game-files.md
> +### Suffix
Will be addressed outside this pR

2022-04-30 23:49 UTC, Unnvaldr approved these changes
Thanks, seems fine now

2022-04-30 23:54 UTC, merged